# Generated by Django 5.1.6 on 2025-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_vendor_title_product_gallery_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
